version: "3.7"

services:
  nginx:
    container_name: qr-menu-proxy
    image: nginx:stable-alpine
    ports:
      - "4000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  postgres-db:
    container_name: qr-menu-postgres
    image: postgres
    # env values defined under each service is accessible only in that container
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data
    expose:
      - "5432"
    #ports:
    #  - "5432:5432"

  redis-db:
    container_name: qr-menu-redis
    image: redis
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    expose:
      - "6379"
    volumes:
      - redis_data:/var/lib/redis/data

  express-server:
    #container_name: qr-menu-api
    build:
      context: .

    image: qr-menu-api-server:0.1.0
    depends_on:
      - postgres-db
      - redis-db
    #if nginx is added, no need to publish our app ports
    #ports:
    #  - "4000:4000"

volumes:
  pg_data:
  redis_data:
